use online_shopping;

-- BASIC PROBLEMS
		-- 1 List all unique cities where customers are located.
				select distinct(geolocation_city) 
				from geolocation;
                
		-- 2. Count the number of orders placed in 2017.
				select count(order_id)
                from orders
                where year(order_purchase_timestamp) = 2017;
                
		-- 3. Find the total sales per category.
				select products.`product category` as ProductCategory , 
                round(sum(order_items.price),2) as Sales
                from order_items
                left join products on order_items.product_id = products.product_id
                group by products.`product category`
                order by sum(order_items.price) DESC;
                
		-- 4. Calculate the percentage of orders that were paid in installments.
				select count(payment_installments) as No_of_Installment,
				payment_installments as Installments,
				round(count(payment_installments) * 100/(select count(order_id)
				from payments),2) as Percentage
				from payments
				group by payment_installments
				order by Percentage desc;
                
		-- 5. Count the number of customers from each state.
				SELECT  customer_city , count(customer_id) as Number_of_Customer
				FROM online_shopping.customer
				group by customer_city
				order by Number_of_Customer desc;
                
                
-- INTERMEDIATE PROBLEMS
		-- 1. Calculate the number of orders per month in 2018.
				select count(order_id) as No_of_Orders,
				monthname(order_purchase_timestamp) as Month_Name
				FROM online_shopping.orders
				where year(order_purchase_timestamp) = 2018
				group by month(order_purchase_timestamp), Month_Name
				order by month(order_purchase_timestamp) asc;
        
        -- 2. Find the average number of products per order grouped by customer city.
				select c.customer_city ,round(avg(order_item_id),2) as Average_No_of_Product
				from order_items oi
				left join orders o on oi.order_id = o.order_id
				left join customer c on o.customer_id = c.customer_id
				group by c.customer_city;
                
        -- 3. Calculate the percentage of total revenue contributed by each product category.
				select p.`product category`,round(sum(oi.price),2) as Total_Sales,
				round(sum(oi.price) * 100 / (select sum(price) from order_items),2) as Percentage_of_Sales
				from order_items oi
				left join products p on oi.product_id = p.product_id
				group by p.`product category`;
                
		-- 4. Identify the correlation between product price and the number of times a product has been purchased.
				SELECT 
				round((COUNT(*) * SUM(price * purchase_count) 
					- SUM(price) * SUM(purchase_count)) /
				SQRT((COUNT(*) * SUM(price * price) - POW(SUM(price),2)) *
					(COUNT(*) * SUM(purchase_count * purchase_count) - POW(SUM(purchase_count),2))
					),2) AS Price_Purchase_Correlation
				FROM
				(SELECT p.`product category`,
						round(AVG(oi.price),2) AS price,
						COUNT(oi.order_item_id) AS purchase_count
					FROM order_items oi
					LEFT JOIN products p 
						ON oi.product_id = p.product_id
					GROUP BY p.`product category`
				) t;
                
		-- 5. Calculate the total revenue generated by each seller and rank them by revenue.
				select  oi.seller_id,
				round(sum(oi.price),2) as Revenue ,
				rank () over (order by sum(oi.price) desc) as seller_rank
				from order_items oi
				group by oi.seller_id
				limit 10;
                
-- ADVANCED PROBLEMS
		-- 1. Calculate the moving average of order values for each customer over their order history.
				SELECT 
				o.customer_id,
				SUM(oi.price) AS order_value,
				ROUND(
					AVG(SUM(oi.price)) OVER (
						PARTITION BY o.customer_id
						ORDER BY o.order_purchase_timestamp
						ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
					), 2
					) AS moving_average
				FROM orders o
				JOIN order_items oi
				ON o.order_id = oi.order_id
				GROUP BY o.customer_id, o.order_id, o.order_purchase_timestamp
				ORDER BY o.customer_id, o.order_purchase_timestamp;

	-- 2. Calculate the cumulative sales per month for each year.
			    select 
				year(o.order_purchase_timestamp) AS year,
				month(o.order_purchase_timestamp) AS month_no,
				monthname(o.order_purchase_timestamp) AS month,
				round(sum(oi.price),2) AS monthly_sales,
				round(sum(sum(oi.price)) over(
						PARTITION BY YEAR(o.order_purchase_timestamp)
						order by month(o.order_purchase_timestamp)),2) as cumulative_sales
				from orders o
				join order_items oi 
					on o.order_id = oi.order_id
				group by year(o.order_purchase_timestamp),
					month(o.order_purchase_timestamp),
					monthname(o.order_purchase_timestamp)
				order by year asc, month_no asc;
    
	-- 3. Calculate the year‑over‑year growth rate of total sales.
				SELECT year,
				round(total_sales,2) as Total_Sales,
				round(LAG(total_sales) OVER (ORDER BY year),2) AS previous_year_sales,
				ROUND(
					((total_sales - LAG(total_sales) OVER (ORDER BY year)) 
					/ LAG(total_sales) OVER (ORDER BY year)) * 100,2) AS yoy_growth_percent
				FROM (SELECT 
					YEAR(o.order_purchase_timestamp) AS year,
					SUM(oi.price) AS total_sales
				FROM orders o
				JOIN order_items oi 
					ON o.order_id = oi.order_id
				GROUP BY YEAR(o.order_purchase_timestamp)) t
				ORDER BY year;
            
	-- 4. Calculate the retention rate of customers (customers who make another purchase within 6 months of their first purchase).
				SELECT 
				COUNT(DISTINCT o2.customer_id) AS customers_within_6_months,
				COUNT(DISTINCT o1.customer_id) AS total_customers,
				ROUND(COUNT(DISTINCT o2.customer_id) / 
					COUNT(DISTINCT o1.customer_id) * 100, 2) AS retention_rate
				FROM(SELECT customer_id,
				MIN(order_purchase_timestamp) AS first_order_date
				FROM orders
				GROUP BY customer_id) o1
				LEFT JOIN orders o2
				ON o1.customer_id = o2.customer_id
				AND o2.order_purchase_timestamp > o1.first_order_date
				AND o2.order_purchase_timestamp <= DATE_ADD(o1.first_order_date, INTERVAL 6 MONTH);            
            
            
	-- 5. Identify the top 3 customers who spent the most money in each year.
				SELECT year, customer_id, total_spent
				FROM (
				SELECT 
				YEAR(o.order_purchase_timestamp) AS year,
				o.customer_id,
				SUM(oi.price) AS total_spent,
				RANK() OVER (
				PARTITION BY YEAR(o.order_purchase_timestamp)
				ORDER BY SUM(oi.price) DESC
				) AS rnk
				FROM orders o
				JOIN order_items oi
				ON o.order_id = oi.order_id
				GROUP BY YEAR(o.order_purchase_timestamp), o.customer_id
				) ranked_customers
				WHERE rnk <= 3;
						
								